pipelines:
  branches:
    master:
      - step:
          name: Run tests and generate coverage report
          image: python:3.12-slim
          script:
            - apt-get update
            - apt-get install -y python3-pip
            - python3 -m pip install --upgrade pip
            - pip install -r requirements.txt
            - pip install coverage
            - coverage run -m pytest
            - coverage report
            - coverage xml
          artifacts:
            - coverage.xml
      - step:
          name: Build a Docker Image
          services:
            - docker
          script:
            - export IMAGE_NAME=text-classifier:v$BITBUCKET_BUILD_NUMBER
            - docker build . -t $IMAGE_NAME -f Dockerfile
      # Save the image to a Container Registry
      # Deploy to Production
definitions:
  services:
    docker:
      memory: 2048